name: Neural Net CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "develop"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt clean test
        with:
          fail_ci_if_error: true